# Generated by Django 2.1.5 on 2019-04-25 15:09

import core.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('bought_value', models.FloatField(null=True)),
                ('sell_value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='users',
        ),
        migrations.AddField(
            model_name='crypto',
            name='logo',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='crypto',
            name='urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=core.models.default_crypto_dict),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='cryptouser',
            name='crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Crypto'),
        ),
        migrations.AddField(
            model_name='cryptouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cryptouser',
            unique_together={('user', 'crypto')},
        ),
    ]
