# Generated by Django 2.1.5 on 2019-01-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('bought_value', models.FloatField(null=True)),
                ('sell_value', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='users',
        ),
        migrations.AddField(
            model_name='cryptouser',
            name='crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Crypto'),
        ),
        migrations.AddField(
            model_name='cryptouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
